services:
  - docker
language: rust
cache: cargo
rust:
  - 1.32.0
branches:
  only:
    - master
    - cross-compile

before_script:
  - rustup component add rustfmt-preview
  - cross --version || cargo install cross
matrix:
  include:
    # Linux
    - name: "Alpine Linux x86_64"
      os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - TEST=1
    - name: "ARM64 Android"
      os: linux
      env:
        - TARGET=aarch64-linux-android
        - TEST=1
    - name: "Linux 32bit"
      os: linux
      env:
        - TARGET=i586-unknown-linux-gnu
        - TEST=1
    # OSX/iOS
    - name: "OSX x86_64"
      os: osx
      env:
        - TARGET=x86_64-apple-darwin
        - TEST=1
    - name: "iOS x86_64"
      os: osx
      env:
        - TARGET=aarch64-apple-ios
        - TEST=1
    # ARM
    - name: "32bit ARM"
      os: linux
      env:
        - TARGET=armv7-unknown-linux-gnueabihf
        - TEST=1

install:
  - rustup target add $TARGET

script:
  - cross build --target $TARGET
  - |
    if [ $TEST = 1 ]; then
      cross test --target $TARGET
    fi
    
#  - cargo build --verbose
#  - cross build --target aarch64-linux-android
#  - cross build --target x86_64-unknown-linux-musl
#  - cross build --target i586-unknown-linux-gnu
#  - cross build --target armv7-unknown-linux-gnueabihf
#  - cargo test --verbose
#  - cross test --target aarch64-linux-android
#  - cross test --target x86_64-unknown-linux-musl
#  - cross test --target i586-unknown-linux-gnu
#  - cross test --target armv7-unknown-linux-gnueabihf
#  - cargo fmt -- --check


