services:
  - docker
language: rust
cache: cargo
rust:
  - 1.32.0
branches:
  only:
    - master
before_script:
  - rustup component add rustfmt-preview
  - cargo install cross
script:
#  - cargo build --verbose
  - cross build --target aarch64-linux-android
#  - cargo test --verbose
  - cross test --target aarch64-linux-android
  - cargo fmt -- --check
